apiVersion: v1
kind: PersistentVolume
metadata:
  name: galaxy-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  glusterfs:
    endpoints: glusterfs
    path: gluster
    readOnly: false
