apiVersion: v1
kind: Secret
metadata: 
  name: grafana-secret
  namespace: monitoring
type: Opaque
data: 
  # echo cellgeni | base64
  # echo "Bainu'z3" | base64
  admin-user: Y2VsbGdlbmk=
  # admin-password: QmFpbnUnejM=
  admin-password: YWRtaW4=